### ISSUE TITLE
Titel Suchergebnis-Kachel auf mobile bitte über Bild?

### ISSUE THREAD

**Issue by annettzobel** [openeduhub/oeh-search-frontend#1]
Im Moment bekommt die mobil Suchende beim Scrollen zuerst das Bild und dann erst den Titel des Mediums. Auf Desktop gut, mobile lieber andersrum
![image](https://user-images.githubusercontent.com/29773981/80817916-935d9c00-8bd2-11ea-80b8-36009bfc8284.jpeg)

**Comment by christopher-l** [comment]
Gelöst mit kompakter Kartenansicht.

![image](https://user-images.githubusercontent.com/1208506/85512991-d5b3c000-b5fa-11ea-8aab-070624b2e4a5.png)
