### ISSUE TITLE
Pagination / Total count always shows 10'000

### ISSUE THREAD

**Issue by programmieraffe** [openeduhub/oeh-search-frontend#15]
![image](https://user-images.githubusercontent.com/777278/87128031-3bf14180-c28f-11ea-86de-cc10d0dc5621.png)

See here (I did not test this solution, but had the same problem while working with elasticsearch)
https://discuss.elastic.co/t/pagination-10000-document-total-limit/214897

**Comment by christopher-l** [comment]
This is indeed intended behavior by ElasticSearch to improve performance. It can be turned off with the mentioned flag, but it might be a good idea to leave it as is to not affect performance negatively.
For now, we updated the text to say "More than 10,000 results" to be more clear to the user. Does this solve the issue for you?

**Comment by programmieraffe** [comment]
Yes, that's way better (and shows the strength of open education ;-))
(Maybe the total count could be shown somewhere else on the page without impacting performance)

**Comment by christopher-l** [comment]
Closing for now because of inactivity. Please reopen, when there are any more specific suggestions / bugs.
