### ISSUE TITLE
Suchergebnisse - rosa Fehlermeldebox kleiner auf Mobilgeräten

### ISSUE THREAD

**Issue by annettzobel** [openeduhub/oeh-search-frontend#2]
Die senkrechten Abstände auf Mobilgeräten könnten besser so sein:
![image](https://user-images.githubusercontent.com/29773981/80818993-71fdaf80-8bd4-11ea-8ae4-bd002e3150ac.png)

**Comment by christopher-l** [comment]
Welches Gerät und sieht das immer noch so aus?

Es sollte so aussehen:
![image](https://user-images.githubusercontent.com/1208506/82063167-6e395500-96cb-11ea-927c-a677b36140dd.png)

**Comment by christopher-l** [comment]
Schließe wegen Inaktivität. Bitte erneut öffnen, wenn das Problem besteht.
