### ISSUE TITLE
Navigationsleiste und Text bei Suchleiste anpassen

### ISSUE THREAD

**Issue by Nele-B** [openeduhub/oeh-search-frontend#21]
- "Über uns" verlinkt jetzt zwar richtig auf "FAQ", aber bitte auch in "FAQ" umbenennen
- "Lernstoff" in Navigationsleiste ist zwar jetzt weg (richtig), aber es steht noch im Text über dem Suchfeld "Finde Lernstoff für digitalen Unterricht" ---> wird zu "Finde Inhalte, Methoden und Tools für den digitalen Unterricht"

**Comment by christopher-l** [comment]
Gefixt in https://github.com/openeduhub/oeh-search-frontend/commit/dc197c1a242052a02601394751e4f6d0519840a9.
