### ISSUE TITLE
"Quelle hinzufügen" Button fehlt

### ISSUE THREAD

**Issue by Basti-OEH** [openeduhub/oeh-search-frontend#5]
Auf der Suche fehlt die Verlinkung zur Seite "Quelle hinzufügen". 

Hier der Link: https://wirlernenonline.de/hinzufuegen/

![grafik](https://user-images.githubusercontent.com/64004102/82062436-64632200-96ca-11ea-95bc-f9016d2d3abc.png)

**Comment by christopher-l** [comment]
@torsten-simon Wird die Wordpress-Seite regelmäßig gecrawlt, so dass die Hinuzgefügten Quellen dann auch wirklich in der Suche auftauchen?

**Comment by torsten-simon** [comment]
@christopher-l Der Crawler `wirlernenonline_spider` macht das. Allerdings müssen wir dann auf dem Server einen Cronjob dafür einrichten, Häufigkeit müssten wir abstimmen, @Basti-OEH reicht das z.b. einmal pro Tag?

**Comment by christopher-l** [comment]
![image](https://user-images.githubusercontent.com/1208506/85512325-10692880-b5fa-11ea-8199-b2d100b3d04d.png)
Gelöst mit Floating-Action-Button unten rechts.
